### ISSUE TITLE
Building on Jetson TX2

### ISSUE THREAD

**Issue by danmartinez78** [apollack11/vive_tracker_loc#2]
I'm trying to build cmake_convert branch on Jetson TX2 to use the ROS node. I'm running into an error 

> In file included from /opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core/core.hpp:48:0,
                 from /home/nvidia/precision_tool/src/vive_tracker_loc/include/posecalc/opencv_pose_calc.h:5,
                 from /home/nvidia/precision_tool/src/vive_tracker_loc/src/poser_pollackpnp.c:9:
/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv2/core.hpp:49:4: error: #error core.hpp header must be compiled as C++
error core.hpp header must be compiled as C++

Any help?

**Comment by jarvisschultz** [comment]
This issue is very likely related to the fact that the project was originally built on OpenCV 2.4.8 which, it seems, allowed headers to be compiled with a C compiler. On OpenCV 3.x, that doesn't seem to be the case anymore. What version of OpenCV are you using? I just pushed a [quick attempt](https://github.com/apollack11/vive_tracker_loc/commit/568b8a0d14c01a428753ddd751c6eb0826728f68) at fixing this issue to the `jarvis_edits` branch. It compiles with no errors or warnings on the 14.04+OpenCV 2.4.8 and the 16.04+OpenCV 3.3.1 machines I had easily accessible. 

**Note** I haven't tested on the real tracker hardware.

**Comment by danmartinez78** [comment]
This commit builds on my machine. Will test with tracker ASAP.

**Comment by skymeson** [comment]
I realize this issue may be resolved but I just checked out the jarvis_edits branch, used the Makefile from the master branch and I'm getting an error. 

vive_tracker_loc-jarvis_edits/src/runposer.c:46: undefined reference to `survive_init'

The makefile is linking to the shared library lib/libsurvive.so which is where I would expect to find survive_init. I'm pretty sure I've cleared my local lib directories of any conflicts with libsurvive. Chances of getting this to build with fresh libsurvive may be slim. Any ideas?

**Comment by skymeson** [comment]
Project builds and runs on my PC, but now I'm testing on a TX2 and I'm running into an issue. The jarvis_edits branch builds but I'm not able to launch runposer without an error. I've added udev rules but not able to open device. 

Loading driver DriverRegHTCVive (0x7f96518678) (1)
Error: Error: cannot open device "HMD" with vid/pid 0bb4:2c87

Did you encounter this on your TX2? Was there a work around, and were you ever able to get pose data on your TX2? Thanks!
